theme: null
remote_theme: sproogen/resume-theme
plugins:
  - jekyll-remote-theme

title: "Elizabeth Mansaray"
description: "Cybersecurity Enthusiast | Security Analyst | IT Professional"
show_downloads: false

# Allow GitHub Pages to use the remote theme
github:
  is_project_page: false
